Implement PERMITTEDLIST_IDS env var
lloesche/valheim-server-docker pull request #352
Opened 2021-05-24 07:09 UTC by vanastassiou

Tested

2021-05-26 10:21 UTC, lloesche commented
@vanastassiou thank you for this PR! Can you please rebase against the current master and add the missing newline in `defaults`? Then we should be good to merge.

2021-05-26 10:21 UTC, lloesche requested changes

2021-05-26 10:21 UTC, lloesche commented on defaults
> +PERMITTEDLIST_IDS=${PERMITTEDLIST_IDS:-}
newline missing

2021-05-31 19:53 UTC, vanastassiou commented on defaults
> +PERMITTEDLIST_IDS=${PERMITTEDLIST_IDS:-}
Added newline

2021-05-31 19:55 UTC, vanastassiou commented
@lloesche Sorry I wasn't clear about the test plan -- those were the steps I planned to have my friend running the server try out when he had time. I didn't want to put that work on you! If you think this PR is safe enough to merge without going through those steps, I'm happy to update the original comment to that effect and mark this ready for review.

2021-06-02 21:10 UTC, lloesche approved these changes

2021-06-02 21:10 UTC, lloesche commented
@vanastassiou seems pretty low risk to me as we're not changing existing behavior. Code looks good to me 👍 🚢

2021-06-02 21:11 UTC, merged