Update valheim-bootstrap
lloesche/valheim-server-docker pull request #366
Opened 2021-06-08 16:34 UTC by FelixReuthlinger

closes https://github.com/lloesche/valheim-server-docker/issues/365

2021-06-08 19:03 UTC, coolguy1771 reviewed
I think it needs to be defined like this `""$valheim_download_path"/steamapps"`

2021-06-08 19:16 UTC, coolguy1771 requested changes
Correction, you don't change it in this file at all. You have to edit the common file where the variable is defined.

```
valheim_download_path=/opt/valheim/dl/server    # Valheim server download directory
valheim_install_path=/opt/valheim/server        # Valheim server installation directory
valheim_restartfile="/tmp/valheim.restart"      # Signaling file created by valheim-updater
```

2021-06-08 19:18 UTC, FelixReuthlinger commented
> Correction, you don't change it in this file at all. You have to edit the common file where the variable is defined.
> 
> ```
> valheim_download_path=/opt/valheim/dl/server    # Valheim server download directory
> valheim_install_path=/opt/valheim/server        # Valheim server installation directory
> valheim_restartfile="/tmp/valheim.restart"      # Signaling file created by valheim-updater
> ```

but the variable itself is fine, it is used the way it is used and shall not change, the problem is just that steamcmd fail on creating the one specific subfolder. Installling the game will anyways still need to be done the exact same way

2021-06-08 19:19 UTC, coolguy1771 commented
> 
> 
> > Correction, you don't change it in this file at all. You have to edit the common file where the variable is defined.
> > ```
> > valheim_download_path=/opt/valheim/dl/server    # Valheim server download directory
> > valheim_install_path=/opt/valheim/server        # Valheim server installation directory
> > valheim_restartfile="/tmp/valheim.restart"      # Signaling file created by valheim-updater
> > ```
> 
> but the variable itself is fine, it is used the way it is used and shall not change, the problem is just that steamcmd fail on creating the one specific subfolder. Installling the game will anyways still need to be done the exact same way

I don't know if you can add a trailing slash like that to create a subfolder that that though.

2021-06-08 20:16 UTC, FelixReuthlinger commented
> > > Correction, you don't change it in this file at all. You have to edit the common file where the variable is defined.
> > > ```
> > > valheim_download_path=/opt/valheim/dl/server    # Valheim server download directory
> > > valheim_install_path=/opt/valheim/server        # Valheim server installation directory
> > > valheim_restartfile="/tmp/valheim.restart"      # Signaling file created by valheim-updater
> > > ```
> > 
> > 
> > but the variable itself is fine, it is used the way it is used and shall not change, the problem is just that steamcmd fail on creating the one specific subfolder. Installling the game will anyways still need to be done the exact same way
> 
> I don't know if you can add a trailing slash like that to create a subfolder that that though.

open for suggestions :D

2021-06-09 06:55 UTC, FelixReuthlinger commented
well, has been added by repo owner without this pr

2021-06-09 06:55 UTC, closed without merging